use customer_behavior;
select * from customer_data;
-- What is the total revenue generated by male and female?

SELECT gender , SUM(purchase_amount) AS revenue
FROM customer_data
GROUP BY gender;

-- Which customers used a discount but still spend more than the avarage purchase amount
 
SELECT ï»¿customer_id,purchase_amount
FROM customer_data
WHERE discount_applied="Yes" AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data );

-- Which are the top 5 product which are the highest avarage review rating
SELECT item_purchased,AVG (review_rating) as "Average Product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG (review_rating) DESC
LIMIT 5;

-- compare the average purchase amount between std and express shipping
SELECT ROUND(AVG(purchase_amount),2),shipping_type
FROM customer_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more ? compare avarage between suscribers and non-suscribers

SELECT subscription_status,
count( ï»¿customer_id) AS total_customer, 
ROUND(AVG(purchase_amount),2) AS Avg_spend ,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue ,avg_spend DESC;


-- Which 5 product have the higest percentage of purchase with discount applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied ='YES' THEN 1 ELSE 0 END)/COUNT(*) ,2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment Customer into new returning and loyal based on their total
-- number of previous purchases, and show the count of each segment.
 
 WITH customer_type as(
 SELECT ï»¿customer_id, previous_purchases,
 CASE 
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_segment
FROM customer_data
 )
 
SELECT customer_segment, COUNT(*) AS "Number of CUstomers"
FROM customer_type
GROUP BY customer_segment;


-- What are the top 3 most purchase product within each category

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(ï»¿customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(ï»¿customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscriber
select subscription_status,
count(ï»¿customer_id)as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribution of each age group

SELECT age_group,
SUM(purchase_amount)as total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;